Keyboard essentials
davidaylaian/carbon pull request #61
Opened 2020-03-30 17:51 UTC by ReewassSquared

ADD TO CHANGELOG:
- created scancode table 1 based on keyboard scancodes for 8042 PS/2 legacy keyboard scheme
- created conditional compilation in kernel/arch/x86/drivers/keyboard.c's `keyboard_install()` which may set the keyboard driver's handler as a callback for IRQ1
- created `__keystate__` to store the bitmap of currently pressed keys
- created `__keystate_ext__` in accordance with extended scancodes for the 8042 PS/2 keyboard
- created `__keyerror__` to store additional information about the keyboard state
- created `keystate_table` and `keystate_ext_table` for scancode to keycode lookups
- created `keyboard_state` struct in kernel/incude/kernel/keyboard.h
- created `keyboard_handler` which updates keyboard state variables accordingly

PLANNED FEATURES:
- use struct `keyboard_state` to store more abstracted information about keyboard state
- implement a circular queue to store keycodes

2020-03-31 01:40 UTC, ReewassSquared commented
ADDITIONAL INFO TO ADD TO CHANGELOG:
- keyboard handler now calls auxiliary update method `update_keyboard_state` which updates `keyboard_state` and takes additional action, depending on which `keyboard_mode` the keyboard driver is in, on the circular queue.
- keyboard driver supports six modes of operation:
1. `KEYALL`: specifies that queue buffer will store keycodes and will halt driver on queue overflow
2. `KEYDUMP`: specifies that queue buffer will store keycodes and will ignore incoming keycodes when queue buffer is full
3. `KEYSMASH`: specifies that queue buffer will store keycodes and will dequeue keycodes without further action to make room for incoming keycodes as needed
4. `TEXTALL`: specifies that queue buffer will store text and will halt driver on queue overflow
5. `TEXTDUMP`: specifies that queue buffer will store text and will ignore incoming text when queue buffer is full
6. `TEXTSMASH`: specifies that queue buffer will store text and will dequeue text without further action to make room for incoming text as needed
- in `keyboard.h`, provides method `keyboard_install` which requires a `keyboard_mode` argument, a buffer argument, and a buffer size argument. Latter two arguments and space inside the buffer are for sole use by the keyboard driver's queue.
- also in `keyboard.h` is a stateful function for converting keycodes to text: `keycode_to_text`
- keycodes or text data in the keyboard driver's queue is retrieved by `next_keycode` (`keyboard.h`)
- added code in `kernel.c` for testing keyboard driver
- added code in `pit.c` for testing keyboard driver (conditional, can be ignored by removing definition of KEYBOARD_DEBUG in `keyboard.h`)
- in `terminal.c`, changed TERMINAL_HEIGHT to reflect the default height used by qemu emulator
- in `terminal.c`, added backspace support.
- in `terminal.c`, fixed scroll function by utilizing `memcpy` and `memset`

2020-03-31 16:24 UTC, davidaylaian requested changes
@ReewassSquared good stuff! I made a cleanup commit at 8c79e4e1ebd167d47f6644e380021993230aea11. Before I rebase and merge, just one more thing: can you `#define` some of the magic numbers used in `keycode_to_text` and `keyboard_handler`?

2020-03-31 17:43 UTC, davidaylaian commented on kernel/kernel/arch/x86/drivers/keyboard.c
> +}
Lots of magic numbers here

2020-03-31 17:43 UTC, davidaylaian commented on kernel/kernel/arch/x86/drivers/keyboard.c
> +void keyboard_handler()
Lots of magic numbers here also

2020-03-31 17:52 UTC, ReewassSquared commented
Will de-mistify code by adding descriptive preprocessor macros for magic numbers

for `keycode_to_text`, the numbers 0x40 and 0x5B (and 0x60 and 0x7B) are the range of alphabetic uppercase and alphabetic lowercase ASCII values, and 0x20 is the constant distance between ASCII alphabetic uppercase and their respective lowercase, and vice versa, which I think doesn't merit magicification.

2020-03-31 17:58 UTC, davidaylaian commented
Could those numbers instead be written as expressions of `'A'`, `'Z'`, `'a'`, and `'z'`? Or, even better: could some of the code be replaced by calls to ctype.h?

2020-03-31 23:10 UTC, BrandonKoerner reviewed
yes

2020-04-01 14:24 UTC, davidaylaian approved these changes

2020-04-01 15:21 UTC, merged